[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/transcribe"
  to = "/.netlify/functions/transcribe"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/download/json"
  to = "/.netlify/functions/download_json"
  status = 200
  force = true

[[redirects]]
  from = "/download/docx"
  to = "/.netlify/functions/download_docx"
  status = 200
  force = true

